sudo: false
language: python
cache: pip

matrix:
  include:
    - {env: TOXENV=style, python: "3.6"}
    - python: "3.6"
    - python: "3.5"
    - python: "3.4"
    - python: "2.7"

install:
  - pip install tox-travis
  - pip install -U pip setuptools

script: tox -v
